# This is a basic workflow to help you get started with Actions

name: Pack-pyinstaller-windows

# Controls when the workflow will run
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Action is Running

      # Runs a set of commands using the runners shell
      - name: Install Scoop & requirements & Pack the py file to exe file
        run: |
          Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
          iex "& {$(irm get.scoop.sh)} -RunAsAdmin"
          scoop install python zip unzip upx -g
          python -m pip install --upgrade pip
          pip3 install requests pyinstaller PySimpleGUI retrying
          pyinstaller ./TiktokDownload-GUI.py
          cd ./dist
          zip -r ./TikTokDownload-GUI.zip ./TiktokDownload-GUI
          ls
          pwd
          
      - uses: actions/upload-artifact@v3
        with:
          name: TikTokDownload-GUI-windows
          path: D:\a\TiktokDownload-GUI\TiktokDownload-GUI\dist\TikTokDownload-GUI.zip
